
name: Update time

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run start
    - name: Commit and push changes
      run: |-
        git add . -A
        git commit -m "Updated time" || exit 0
        git push
